sylius_grid:
    grids:
        app_admin_blog_post:
            driver:
                name: doctrine/orm
                options:
                    class: App\Entity\Blog\BlogPost
            sorting:
                createdAt: desc
            fields:
                title:
                    type: string
                    label: Titre de l'article
                slug:
                    type: string
                    label: Slug (URL)
                published:
                    type: twig
                    label: Publie
                    options:
                        template: "@SyliusAdmin/shared/grid/field/boolean.html.twig"
                createdAt:
                    type: datetime
                    label: Date de creation
                    options:
                        format: d/m/Y H:i
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete
        app_admin_project_request:
            driver:
                name: doctrine/orm
                options:
                    class: App\Entity\ProjectRequest
            sorting:
                createdAt: desc
            fields:
                createdAt:
                    type: datetime
                    label: Date
                    options:
                        format: d/m/Y H:i
                product:
                    type: string
                    label: Produit ciblé
                    path: product.name
                firstName:
                    type: string
                    label: Prénom
                lastName:
                    type: string
                    label: Nom
                status:
                    type: twig
                    label: Statut
                    options:
                        template: "admin/project_request/grid/field/status.html.twig"
            filters:
                status:
                    type: string
                firstName:
                    type: string
                lastName:
                    type: string
            actions:
                main: ~
                item:
                    update:
                        type: update
                    delete:
                        type: delete
