# @see https://stack.sylius.com/resource/index
sylius_resource:
    # Override default settings
    #settings:

    # Configure the mapping for your resources
    mapping:
        paths:
            - '%kernel.project_dir%/src/Entity'

    # Configure your resources
    resources:
        app.product_audio:
            driver: doctrine/orm
            classes:
                model: App\Entity\Product\ProductAudio

        app.blog_post:
            driver: doctrine/orm
            classes:
                model: App\Entity\Blog\BlogPost
                repository: App\Repository\BlogPostRepository
                form: App\Form\Type\BlogPostType

        app.product_technical_sheet_item:
            driver: doctrine/orm
            classes:
                model: App\Entity\Product\ProductTechnicalSheetItem
                form: App\Form\Type\ProductTechnicalSheetItemType
            translation:
                classes:
                    model: App\Entity\Product\ProductTechnicalSheetItemTranslation
                    form: App\Form\Type\ProductTechnicalSheetItemTranslationType

        app.project_request:
            driver: doctrine/orm
            classes:
                model: App\Entity\ProjectRequest
                form: App\Form\Type\ProjectRequestType

